# Generated by Django 4.2.5 on 2023-12-04 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingCart', '0006_remove_feedback_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='updated',
        ),
    ]
