# Generated by Django 4.2.5 on 2023-12-04 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingCart', '0007_remove_feedback_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='status',
        ),
    ]
