# Generated by Django 4.2.7 on 2023-12-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0003_order_order_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='proyect/product_images'),
        ),
    ]
