# Generated by Django 4.2.5 on 2023-11-12 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_delete_category_obra_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AlterModelOptions(
            name='obra',
            options={'ordering': ['name']},
        ),
    ]
