# Generated by Django 4.2.5 on 2023-11-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('NATURALEZA_MUERTA', 'Naturaleza muerta'), ('RETRATO', 'Retrato'), ('PAISAJE', 'Paisaje'), ('ABSTRACTO', 'Abstracto'), ('FIGURATIVO', 'Figurativo')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('opinions', models.JSONField(blank=True, null=True)),
                ('manufacturer', models.CharField(max_length=100)),
            ],
        ),
    ]
