# Generated by Django 4.2.5 on 2023-11-14 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='created_by',
        ),
    ]
