# Generated by Django 4.2.7 on 2023-11-23 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_order_order_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='custumer',
        ),
    ]
