# Generated by Django 4.2.5 on 2023-11-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_delete_product_alter_obra_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images'),
        ),
    ]
