# Generated by Django 4.2.5 on 2023-11-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_obra_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Still Life', 'Still Life'), ('Portrait', 'Portrait'), ('Landscape', 'Landscape'), ('Abstract', 'Abstract'), ('Figurative', 'Figurative'), ('Other', 'Other')], default='Portrait', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('opinions', models.JSONField(blank=True, null=True)),
                ('manufacturer', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='Obra',
        ),
    ]
