# Generated by Django 4.2.7 on 2023-11-23 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_customer_order_custumer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='custumer',
            new_name='customer',
        ),
    ]
