# Generated by Django 4.2.7 on 2023-11-25 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_custumer_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_detail',
            name='order',
        ),
        migrations.RemoveField(
            model_name='order_detail',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Order_Detail',
        ),
    ]
