# Generated by Django 4.2.5 on 2023-12-08 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
